Repository 2110-FTB-PT/cyber-knights, pull requests merged in 2022-03, with the labels that each got.

#9 05 init db setup
  README.md
  db/client.js
  db/index.js
  db/init_db.js
  db/seedData.js
  index.js
  jest.config.js
  package-lock.json
  package.json
  public/index.html
  tests/db.spec.js
Labels: Init

#26 added helper function and updated updateReview
  db/models/reviews.js
  tests/db.spec.js
Labels: Update

#27 Added some error handling into db/reviews functions
  db/models/reviews.js
  db/seedData.js
  tests/db.spec.js
Labels: Update

#31 Review routes api
  api/apiRouter.test.js
  api/index.js
  api/reviews.js
  api/utils.js
  db/seedData.js
  index.js
  tests/db.spec.js
Labels: enhancement, Update

#34 Added db images.js file, api images.js file, added muter to upload i…
  .DS_Store
  api/images.js
  api/index.js
  db/index.js
  db/models/images.js
  package-lock.json
  package.json
  public/.DS_Store
  public/product/.DS_Store
  public/product/1647718854038--Screen Shot 2022-02-27 at 10.22.07 PM.png
  public/product/1647719419611--Screen Shot 2022-02-27 at 10.22.07 PM.png
  public/review/.DS_Store
  public/review/1647717536493--Screen Shot 2022-02-27 at 10.22.07 PM.png
  public/review/1647717556703--Screen Shot 2022-02-27 at 10.22.07 PM.png
  public/review/1647717612227--Screen Shot 2022-02-27 at 10.22.07 PM.png
  public/review/1647717630711--Screen Shot 2022-02-27 at 10.22.07 PM.png
  public/review/1647718602740--Screen Shot 2022-02-27 at 10.22.07 PM.png
  public/review/1647718734728--Screen Shot 2022-02-27 at 10.22.07 PM.png
  public/review/1647718768008--Screen Shot 2022-02-27 at 10.22.07 PM.png
Labels: enhancement

#35 added Admin table and seeded admin accounts
  db/models/users.js
  db/seedData.js
Labels: bug, enhancement

#46 mostUpdateddest of codes
  api/products.js
  db/models/users.js
  db/seedData.js
Labels: Update

#47 moved 404 handler into api/index.js
  api/index.js
  api/products.js
  index.js
Labels: Update

#61 New api routes
  api/reviews.js
  db/seedData.js
  package.json
Labels: bug

#72 New new home component
  api/reviews.js
  db/models/reviews.js
  db/seedData.js
  src/axios-services/index.js
  src/components/App.js
  src/components/Home.jsx
  src/components/HomeCarousel.jsx
  src/components/HomeReviews.jsx
Labels: enhancement
